version: "3.9"
services:
  mysql:
    image: mysql:latest
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3309:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
  
  app:
    build: ./app  
    restart: always
    depends_on:
      - mysql
    ports:
      - 5001:5000
    env_file:
      - .env

  nginx:  
    image: nginx:latest
    platform: linux/amd64
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app

volumes:
  mysql_data:
